/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubesgo;

import javax.swing.JFrame;

/**
 *
 * @author ACER-PC
 */
public class Gameover extends javax.swing.JFrame {

    /**
     * Creates new form Gameover
     */
    Skor skor;
    public Gameover() {
        
    }
    
    public Gameover(Skor skor) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.skor = skor;
        int s1 = skor.playerOneScore();
        int s2 = skor.playerTwoScore();
        p1.setText(Username.Namapemain1);
        p2.setText(Username.Namapemain2);
        score1.setText(s1 + " ");
        score2.setText(s2 + " ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(485, 340));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELESAI");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 260, 20);

        next.setBackground(new java.awt.Color(255, 255, 255));
        next.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        next.setForeground(new java.awt.Color(102, 255, 51));
        next.setText("SELANJUTNYA");
        next.setBorderPainted(false);
        next.setContentAreaFilled(false);
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.setDefaultCapable(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next);
        next.setBounds(290, 260, 160, 20);

        p1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        p1.setForeground(new java.awt.Color(102, 255, 51));
        p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1.setText("Player 1");
        getContentPane().add(p1);
        p1.setBounds(140, 70, 100, 50);

        p2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        p2.setForeground(new java.awt.Color(102, 255, 51));
        p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2.setText("Player 2");
        getContentPane().add(p2);
        p2.setBounds(140, 160, 100, 50);

        score1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        score1.setForeground(new java.awt.Color(102, 255, 51));
        score1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score1.setText("0");
        getContentPane().add(score1);
        score1.setBounds(240, 70, 90, 50);

        score2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        score2.setForeground(new java.awt.Color(102, 255, 51));
        score2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score2.setText("0");
        getContentPane().add(score2);
        score2.setBounds(240, 160, 100, 50);

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER-PC\\OneDrive\\Documents\\NetBeansProjects\\TUBESGO\\src\\img\\lapangan.png")); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 480, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        Koneksi kon = new Koneksi();

        kon.buatSkor(skor.playerOneScore(),skor.playerTwoScore(),Username.Namapemain1,Username.Namapemain2);
        setVisible(false);
        MenuAwal menu = new MenuAwal();
        menu.setVisible(true);
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gameover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gameover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gameover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gameover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Gameover().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton next;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    // End of variables declaration//GEN-END:variables
}
