/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubesgo;

import javax.swing.ImageIcon;

/**
 *
 * @author ACER-PC
 */
public class MenuAwal extends javax.swing.JFrame {

    /**
     * Creates new form MenuAwal
     */
    
    Music musik = new Music();
    
    public MenuAwal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        musik.run();
        
        on.setEnabled(!Tmp.buttonState);
        OFF.setEnabled(Tmp.buttonState);
        on.setVisible(!Tmp.buttonState);
        OFF.setVisible(Tmp.buttonState);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mulai = new javax.swing.JButton();
        Pengaturan = new javax.swing.JButton();
        Riwayat = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        on = new javax.swing.JButton();
        OFF = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 360));
        getContentPane().setLayout(null);

        Mulai.setBackground(new java.awt.Color(255, 255, 255));
        Mulai.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        Mulai.setForeground(new java.awt.Color(102, 255, 51));
        Mulai.setText("MULAI");
        Mulai.setBorderPainted(false);
        Mulai.setContentAreaFilled(false);
        Mulai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mulai.setDefaultCapable(false);
        Mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MulaiActionPerformed(evt);
            }
        });
        getContentPane().add(Mulai);
        Mulai.setBounds(190, 240, 90, 20);

        Pengaturan.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        Pengaturan.setForeground(new java.awt.Color(102, 255, 51));
        Pengaturan.setText("PENGATURAN");
        Pengaturan.setBorderPainted(false);
        Pengaturan.setContentAreaFilled(false);
        Pengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PengaturanActionPerformed(evt);
            }
        });
        getContentPane().add(Pengaturan);
        Pengaturan.setBounds(170, 280, 140, 20);

        Riwayat.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        Riwayat.setForeground(new java.awt.Color(102, 255, 51));
        Riwayat.setText("RIWAYAT");
        Riwayat.setContentAreaFilled(false);
        Riwayat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Riwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiwayatActionPerformed(evt);
            }
        });
        getContentPane().add(Riwayat);
        Riwayat.setBounds(80, 280, 110, 20);

        Keluar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        Keluar.setForeground(new java.awt.Color(102, 255, 51));
        Keluar.setText("KELUAR");
        Keluar.setContentAreaFilled(false);
        Keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(290, 280, 100, 20);

        on.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        on.setForeground(new java.awt.Color(102, 255, 51));
        on.setText("ON");
        on.setBorderPainted(false);
        on.setContentAreaFilled(false);
        on.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });
        getContentPane().add(on);
        on.setBounds(140, 10, 100, 20);

        OFF.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        OFF.setForeground(new java.awt.Color(102, 255, 51));
        OFF.setText("OFF");
        OFF.setToolTipText("");
        OFF.setBorderPainted(false);
        OFF.setContentAreaFilled(false);
        OFF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFFActionPerformed(evt);
            }
        });
        getContentPane().add(OFF);
        OFF.setBounds(240, 10, 100, 20);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/25462_ebccf7ef3916599d636a18f7d91e58b3.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 480, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MulaiActionPerformed
        this.setVisible(false);
        new Username().setVisible(true);
    }//GEN-LAST:event_MulaiActionPerformed

    private void RiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiwayatActionPerformed
        this.setVisible(false);
        new Score().setVisible(true);                                    
    }//GEN-LAST:event_RiwayatActionPerformed

    private void PengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PengaturanActionPerformed
        this.setVisible(false);
        new Pengaturan().setVisible(true);
    
    }//GEN-LAST:event_PengaturanActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_KeluarActionPerformed

    private void OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFFActionPerformed
       musik.clip.stop();
       OFF.setEnabled(false);
       OFF.setVisible(false);
       on.setVisible(true);
       on.setEnabled(true);
//       on.setEnabled(true);
//       on.setVisible(false);
       Tmp.buttonState=(true);
    }//GEN-LAST:event_OFFActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed
       musik.clip.start();
       OFF.setEnabled(true);
       OFF.setVisible(true);
       on.setVisible(false);
       on.setEnabled(false);
       Tmp.buttonState=(false);
    }//GEN-LAST:event_onActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Mulai;
    private javax.swing.JButton OFF;
    private javax.swing.JButton Pengaturan;
    private javax.swing.JButton Riwayat;
    private javax.swing.JButton on;
    // End of variables declaration//GEN-END:variables
}
